#pragma once

#include "ti_msp_dl_config.h"
#include "constants.h"

/*!
 * @brief Group Permissions Structure
 */
/*!
 * @brief Group permissions structure
 */
typedef struct {
    //! Read permission flag
    bool read;

    //! Write permission flag
    bool write;

    //! Transfer permission flag
    bool transfer;
} group_permissions_t;

/*!
 * @brief Group Private Keys Structure
 *
 * In our current implementation all the keys should be the same
 * size and format even though we are using different algorithms
 * in mbedtls. All the keys should be 32 bytes (storing 255 bits).
 * A provisioned HSM will only have the keys for permissions that the
 * HSM has. Eg. if an HSM is provisioned for Reading and Transfering for
 * a group it will only the read_key and transfer_key fields will be valid
 * in the corresponding group structure.
 * 
 * For more information refer to the [PSA Crypto API](https://arm-software.github.io/psa-api/crypto/1.4/api/keys/types.html#elliptic-curve-families)
 * 
 * @pre read_key is valid if and only if permissions.read is true
 * @pre write_key is valid if and only if permissions.write is true
 * @pre transfer_key is valid if and only if permissions.transfer is true
 */
/*!
 * @brief Group private keys structure
 * 
 * Each group has separate private keys for different permissions.
 * Only keys for granted permissions are stored.
 */
typedef struct {
    //! Group permissions
    group_permissions_t permissions;

    //! Group read private key (32 bytes)
    uint8_t read_key[32];

    //! Group write private key (64 bytes for Ed25519)
    uint8_t write_key[64];

    //! Group transfer private key (32 bytes)
    uint8_t transfer_key[32];
} group_private_t;

/*!
 * @brief Group Public Keys Structure
 * 
 * Every provisioned HSM must contain the public keys
 * for all the permissions of every group.
 */
/*!
 * @brief Group public keys structure
 * 
 * Every provisioned HSM must contain the public keys
 * for all permissions of every group.
 */
typedef struct {
    //! Group read public key (32 bytes for X25519)
    uint8_t read_key[32];

    //! Group write public key (32 bytes for Ed25519)
    uint8_t write_key[32];

    //! Group transfer public key (32 bytes)
    uint8_t transfer_key[32];
} group_public_t;

/*!
 * @brief Group Structure as Stored on Flash
 *
 * A const array of this structure should be generated by
 * the host tools for each HSM. The const qualifier tells
 * the compiler to store the data in the .rodata section
 * on the flash as stated in the
 * [TI Arm Clang Compiler Tools User's Guide](https://software-dl.ti.com/codegen/docs/tiarmclang/compiler_tools_user_guide/compiler_manual/c_cpp_language_implementation/keywords.html).
 */
typedef struct {
    //! Group identifier
    uint16_t group_id;

    //! Group public keys
    group_public_t public;

    //! Group private keys
    group_private_t private;
} group_t;