#pragma once

#include "ti_msp_dl_config.h"
#include "constants.h"

/*!
 * @brief Group Permissions Structure
 */
typedef struct {
    bool read;
    bool write;
    bool transfer;
} group_permissions_t;

/*!
 * @brief Group Private Keys Structure
 *
 * In our current implementation all the keys should be the same
 * size and format even though we are using different algorithms
 * in mbedtls. All the keys should be 32 bytes (storing 255 bits).
 * A provisioned HSM will only have the keys for permissions that the
 * HSM has. Eg. if an HSM is provisioned for Reading and Transfering for
 * a group it will only the read_key and transfer_key fields will be valid
 * in the corresponding group structure.
 * 
 * For more information refer to the [PSA Crypto API](https://arm-software.github.io/psa-api/crypto/1.4/api/keys/types.html#elliptic-curve-families)
 * 
 * @pre read_key is valid if and only if permissions.read is true
 * @pre write_key is valid if and only if permissions.write is true
 * @pre transfer_key is valid if and only if permissions.transfer is true
 */
typedef struct {
    group_permissions_t permissions;
    uint8_t read_key[32];
    uint8_t write_key[64];
    uint8_t transfer_key[32];
} group_private_t;

/*!
 * @brief Group Public Keys Structure
 * 
 * Every provisioned HSM must contain the public keys
 * for all the permissions of every group.
 */
typedef struct {
    uint8_t read_key[32];
    uint8_t write_key[32];
    uint8_t transfer_key[32];
} group_public_t;

/*!
 * @brief Group Structure as Stored on Flash
 *
 * A const array of this structure should be generated by
 * the host tools for each HSM. The const qualifier tells
 * the compiler to store the data in the .rodata section
 * on the flash as stated in the
 * [TI Arm Clang Compiler Toools User's Guide](https://software-dl.ti.com/codegen/docs/tiarmclang/compiler_tools_user_guide/compiler_manual/c_cpp_language_implementation/keywords.html).
 */
typedef struct {
    //! Group Identifier
    uint16_t group_id;

    //! Group Private Key Data
    group_public_t public;

    //! Group Public Key Data
    group_private_t private;
} group_t;