# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Build Documentation

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - docs
      - firmware/include
      - firmware/src
    
permissions:
  contents: read
  pages: write
  id-token: write
    
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    
    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          mkdir build
          cd build
          cmake ../firmware
          make docs
          
    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: "build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
