# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Lint Codebase

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          cmake -B build
          cd build
          make lint-ci
